# Generated by Django 3.1 on 2020-08-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bidang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaBidang', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='jab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaJabatan', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='legalitas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='', max_length=255)),
                ('image', models.FileField(default='', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='sejarah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaSub', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='strukturOrganisasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='', max_length=255)),
                ('keterangan', models.CharField(default='', max_length=255)),
                ('foto', models.FileField(blank=True, default='', null=True, upload_to='')),
                ('status', models.ManyToManyField(blank=True, default='', to='tentang.bidang')),
            ],
        ),
        migrations.CreateModel(
            name='daftarAsesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaAsesor', models.CharField(default='', max_length=255)),
                ('jabatan', models.ManyToManyField(blank=True, default='', to='tentang.jab')),
                ('subBidang', models.ManyToManyField(blank=True, default='', to='tentang.sub')),
            ],
        ),
    ]
