# Generated by Django 3.1 on 2020-09-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengalamanKontakForm', '0002_auto_20200902_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='jenisGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='dokumentasi',
            name='jenis',
            field=models.ManyToManyField(blank=True, default='', to='pengalamanKontakForm.jenisGallery'),
        ),
    ]
